export const GOOGLE_SIGNIN_REQUEST = 'GOOGLE_SIGNIN_REQUEST';
export const GOOGLE_SIGNIN_SUCCESS = 'GOOGLE_SIGNIN_SUCCESS';
export const GOOGLE_SIGNIN_FAILURE = 'GOOGLE_SIGNIN_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE ';
export const SIGN_OUT = 'SIGN_OUT';
